version: '3.8'

services:
  qstash:
    image: public.ecr.aws/upstash/qstash:latest
    ports:
      - '8081:8080'

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
